version: '3.7'
services:
  proxy-reverse:
    image: nginx
    restart: always
    ports:
      - 9060:9060
    volumes: 
      - /usr/local/Proyectos/Galaxy/DockerK8S-202108/Lab08/SOL/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
       - backend      
  backend:
      image: galaxy202108.azurecr.io/ggonzales/apinode:1.0.0
      container_name: backend
      restart: always
      ports:
        - 3000:3000
      environment:
        URL_DB: 'mongodb://mongo:27017/interfaces'
        URL_DB_USER: root
        URL_DB_PWD: "pwd123456!"
      depends_on: 
        - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "pwd123456!"
      MONGO_INITDB_DATABASE: interfaces
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: "pwd123456!"